theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    footer: "/assets/images/logo-white.svg"
  default:
    single:
      meta:
        options:
          with_labels: false
  breadcrumb:
    position: after-hero
  image_sizes:
    _default:
      hero:
        mobile:   400
        tablet:   800
        desktop:  1440
    sections:
      posts:
        hero_single:
          mobile:   400
          tablet:   800
          desktop:  1440
